# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=255, null=True)),
                ('temperatura', models.CharField(max_length=255, null=True)),
                ('condicao', models.CharField(max_length=255, null=True)),
                ('sensacao', models.CharField(max_length=255, null=True)),
                ('humidade', models.CharField(max_length=255, null=True)),
                ('pressao', models.CharField(max_length=255, null=True)),
                ('vento', models.CharField(max_length=255, null=True)),
                ('atualizacao', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
